### ISSUE TITLE
4.1 doc结尾出现错误

### ISSUE THREAD

**Issue by lijiayu0725** [ShusenTang/Dive-into-DL-PyTorch#1]
Sequential、ModuleList、ModuleDict类继承自BlModuleock类。
最后应该是继承Module类吧。
感谢大佬给初学者提供PyTorch框架版！

**Comment by ShusenTang** [comment]
> Sequential、ModuleList、ModuleDict类继承自BlModuleock类。
> 最后应该是继承Module类吧。
> 感谢大佬给初学者提供PyTorch框架版！

已纠正，谢谢提醒
