### ISSUE TITLE
3.3.4节报错：'LinearNet' object does not support indexing

### ISSUE THREAD

**Issue by JianJuly** [ShusenTang/Dive-into-DL-PyTorch#10]
python版本为3.6.3
pytorch版本为1.2.0

建议将原代码
```python
init.normal_(net[0].weight, mean=0, std=0.01)
init.constant_(net[0].bias, val=0)  # 也可以直接修改bias的data: net[0].bias.data.fill_(0)
```
更改为：
```python
init.normal_(net.linear.weight, mean=0, std=0.01)
init.constant_(net.linear.bias, val=0)  # 也可以直接修改bias的data: net[0].bias.data.fill_(0)
```

**Comment by yongboy** [comment]
其实，这里不需要修改。

原因：写法三所创建 `net` 为 `nn.Sequentia` 数组对象，可见下面代码：

``` python
# 写法三
from collections import OrderedDict
net = nn.Sequential(OrderedDict([
          ('linear', nn.Linear(num_inputs, 1))
          # ......
        ]))

print(net)
print(net[0])
```

**Comment by JianJuly** [comment]
> 其实，这里不需要修改。
> 
> 原因：写法三所创建 `net` 为 `nn.Sequentia` 数组对象，可见下面代码：
> 
> ```python
> # 写法三
> from collections import OrderedDict
> net = nn.Sequential(OrderedDict([
>           ('linear', nn.Linear(num_inputs, 1))
>           # ......
>         ]))
> 
> print(net)
> print(net[0])
> ```

抱歉哈，我用的第一种方法，所以报错了，建议这里稍微注释一下，因为很多人会使用第一种方法

**Comment by ShusenTang** [comment]
如果`net`是用3.3.3节一开始的代码自定义的，那么就会报错，`net[0].weight`应改为`net.linear.weight`，`bias`亦然。因为`net[0]`这样根据下标访问子模块的写法只有当`net`是个`ModuleList`或者`Sequential`实例时才可以，详见4.1节。
