### ISSUE TITLE
麻烦请求作者先放一个PDF版本合集 .md文件下载后 有大量公式显示不全 阅读障碍严重

### ISSUE THREAD

**Issue by chenhaishun** [ShusenTang/Dive-into-DL-PyTorch#11]

**Comment by jianpingbadao** [comment]
Duplicate of #6 ?

**Comment by yongboy** [comment]
当前虽然没有制作PDF文件，推荐在Mac或Linux下：

- `git clone https://github.com/yongboy/Dive-into-DL-PyTorch.git`
- 终端下执行`make wwwdocs`命令
- 在本地浏览器访问 `http://127.0.0.1:3000/` 即可完整显示所有数学公式了

**Comment by ShusenTang** [comment]
[《动手学深度学习》(PyTorch版)网页版](http://shusentang.github.io/Dive-into-DL-PyTorch/)现已推出，公式完美渲染，感谢持续关注
