### ISSUE TITLE
关于Chap02中2.3_autograd.ipynb的疑问

### ISSUE THREAD

**Issue by simonwangwxm** [ShusenTang/Dive-into-DL-PyTorch#12]
原文中写到

> 如果我们想要修改tensor的数值，但是又不希望被autograd记录（即不会影响反向传播），那么我么可以对tensor.data进行操作.

```
In [14]:
x = torch.ones(1,requires_grad=True)

print(x.data) # 还是一个tensor
print(x.data.requires_grad) # 但是已经是独立于计算图之外

y = 2 * x
x.data *= 100 # 只改变了值，不会记录在计算图，所以不会影响梯度传播

y.backward()
print(x) # 更改data的值也会影响tensor的值
print(x.grad)
```

-----------输出结果-----------
tensor([1.])
False
tensor([100.], requires_grad=True)
tensor([2.])

我做了些尝试性的改变，发现输出了一些我无法理解的结果，比如把`y = 2 * x
`改成`y = 2 * x * x`时，`print(x.grad)`的输出结果变成`202`；如果把`y = 2 * x`改成`y = 2 * x * x * x`，`print(x.grad)`的输出结果变成`20202`。

虽然结果似乎有一定的规律，但是我没找到。这种情况下应该怎么解释呢？

**Comment by caoshuai619** [comment]
pytorch会进行自动的梯度累加

**Comment by simonwangwxm** [comment]
累加我同意，但是导数不对啊。

假设累加的情况不变（不把前面的梯度zero out），

比如这里，我把`y = 2 * x`改成`y = 2 * x * x`，其他不变，同样的程序运行一次。`print(x.grad)`不是应该会输出`6`吗？为什么会输出`202`呢？

而且，这里好像不是累加的问题。因为我单独运行修改后的程序，输出结果还是202。

**Comment by biggoood** [comment]
pytorch在这里先计算2 * a的梯度，再计算a * a的梯度，累加为2 + 2 * a。修改为 y = 2 * a ** 2后可以得到预期结果。这个计算可能是动态图的运算特点造成的。

**Comment by simonwangwxm** [comment]
> pytorch在这里先计算2 * x的梯度，再计算x * x的梯度，累加为2 + 2 * x。修改为 y = 2 * x ** 2后可以得到预期结果。这个计算可能是动态图的运算特点造成的。

您好，如果我想了解更多的关于，动态图的运算特点，就像你说的这种特性，有什么比较优秀的针对性的学习资料吗？

**Comment by biggoood** [comment]
> > pytorch在这里先计算2 * x的梯度，再计算x * x的梯度，累加为2 + 2 * x。修改为 y = 2 * x ** 2后可以得到预期结果。这个计算可能是动态图的运算特点造成的。
> 
> 您好，如果我想了解更多的关于，动态图的运算特点，就像你说的这种特性，有什么比较优秀的针对性的学习资料吗？

这个repo里第八章讲的命令式和符号式就是这两种运算方式。其他的可以通过对比[tensorflow](https://tensorflow.google.cn/learn)和[pytorch](https://pytorch.org/docs/stable/index.html)的介绍文档来看

**Comment by simonwangwxm** [comment]
> > > pytorch在这里先计算2 * x的梯度，再计算x * x的梯度，累加为2 + 2 * x。修改为 y = 2 * x ** 2后可以得到预期结果。这个计算可能是动态图的运算特点造成的。
> > 
> > 
> > 您好，如果我想了解更多的关于，动态图的运算特点，就像你说的这种特性，有什么比较优秀的针对性的学习资料吗？
> 
> 这个repo里第八章讲的命令式和符号式就是这两种运算方式。其他的可以通过对比[tensorflow](https://tensorflow.google.cn/learn)和[pytorch](https://pytorch.org/docs/stable/index.html)的介绍文档来看

好的，谢谢，我仔细查看一下。那按照我以前的问题来看，您的解释可以解释`y = 2 * x * x`的运行结果为什么是`202`，那如果是`y = 2 * x * x * x`，输出结果为什么是`20202`呢？您能按照您的思路拓展一下吗？

**Comment by biggoood** [comment]
@simonwangwxm 为了方便理解可以把2 * x * x * x拆分成三个函数：
a = 2 * x
b = a * x
c = b * x
pytorch中的backward()函数会自动对每个变量进行求导，并对相同变量的梯度进行累加。从c开始，c调用backward()函数后会对b和x求导，然后b的导数会对a和x求导，a最后对x求导。
x.grad_c = b = 2 * x * x = 20000
x.grad_b = a = 2 * x = 200
x.grad_a = 2
所以x.grad = x.grad_c + x.grad_b + x.grad_a = 20202

**Comment by simonwangwxm** [comment]
@biggoood 懂了，原来是这样，谢谢🙏
