### ISSUE TITLE
5.7   对于语法的疑惑   为什么blk前面会有一个星号呢    

### ISSUE THREAD

**Issue by resplendent-star** [ShusenTang/Dive-into-DL-PyTorch#121]
![a](https://user-images.githubusercontent.com/41502003/79548222-b020ac80-80c7-11ea-9953-ecbe771306df.png)

**Comment by ShusenTang** [comment]
这是python传多个参数的语法，可参考https://www.jianshu.com/p/be92113116c8

**Comment by resplendent-star** [comment]
好的谢谢(*°∀°)=3恕我无知------------------ 原始邮件 ------------------
发件人: "ShusenTang"<notifications@github.com>
发送时间: 2020年4月17日(星期五) 下午4:28
收件人: "ShusenTang/Dive-into-DL-PyTorch"<Dive-into-DL-PyTorch@noreply.github.com>;
抄送: "resplendent-star"<485434977@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ShusenTang/Dive-into-DL-PyTorch] 5.7   对于语法的疑惑   为什么blk前面会有一个星号呢     (#121)




 
这是python传多个参数的语法，可参考https://www.jianshu.com/p/be92113116c8
 
&mdash;
