### ISSUE TITLE
继续请教前辈，ch5 vggnet 这里 x=blx（x）语法实在无法理解，谢谢前辈

### ISSUE THREAD

**Issue by resplendent-star** [ShusenTang/Dive-into-DL-PyTorch#122]
![blx](https://user-images.githubusercontent.com/41502003/79553476-1f4dcf00-80cf-11ea-9630-32580fd4c66c.png)

**Comment by ShusenTang** [comment]
blk是一个module，`output = blk(input)`就相当于调用blk的前向传播函数

**Comment by resplendent-star** [comment]
> blk是一个模块，`output = blk(input)`就相当于调用blk的前向传播函数

啊，谢谢前辈回复，这python看起来语法很简单，但是让人总是很迷，不像c++每一个变量类型函数返回值都清清楚楚，看python代码每个都不知道类型（捂脸）

BTW：这种用法是怎么学会的呀，看pytorch文档嘛

**Comment by ShusenTang** [comment]
> > blk是一个模块，`output = blk(input)`就相当于调用blk的前向传播函数
> 
> 啊，谢谢前辈回复，这python看起来语法很简单，但是让人总是很迷，不像c++每一个变量类型函数返回值都清清楚楚，看python代码每个都不知道类型（捂脸）
> 
> BTW：这种用法是怎么学会的呀，看pytorch文档嘛

嗯，PyTorch官方文档就有介绍
