### ISSUE TITLE
2.2.4 运算的内存开销 中关于view之后是否是同一id的疑惑

### ISSUE THREAD

**Issue by asuith** [ShusenTang/Dive-into-DL-PyTorch#13]
教程中的表述，虽然没有明说，不过给人感觉是view这种操作不会改变id值。

但在我试验中，tensor在view之后，会变为新的id。如下代码：

```python
x = torch.randn(1,2)
print(x)
y = x.view(1,2)
print(y)
print(id(x) == id(y))

```

> tensor([[-0.7329, -1.4493]])
tensor([[-0.7329, -1.4493]])
False

不过使用torch自带的equal可以正确检查这两个是不是指向同一个tensor：

```python
x = torch.zeros(3, 5)
y = x.view(3, 5)

print(torch.equal(x, y))
```

> True

不过equal函数要求tensor有相同的size和elements。

**Comment by raycool** [comment]
应该使用data_ptr()函数来输出Tensor的第一个元素的内存地址
而Tensor数据类型不仅包含data，还包含一些其他内容
所以使用view函数虽然不改变data在内存中的排列，但是会改变Tensor中别的属性的值
所以使用id会造成不同。

**Comment by asuith** [comment]
之前没有说清楚，我是想说，教程中可以修改一下，因为原文中暗示的意思是错的。

> 2.2.4 运算的内存开销

> 前面说了，索引、view是不会开辟新内存的，而像y = x + y这样的运算是会新开内存的，然后将y指向新内存。为了演示这一点，我们可以使用Python自带的id函数：如果两个实例的ID一致，那么它们所对应的内存地址相同；反之则不同。
