### ISSUE TITLE
能否先根据目前的版本制作一个pdf，方便推广

### ISSUE THREAD

**Issue by adrain-huang** [ShusenTang/Dive-into-DL-PyTorch#14]
请问能否根据现在目前已有的版本生成一个pdf，这样阅读起来方便，阅读的人也会增加很多，方便项目推广。大家边阅读边反馈，最终版的质量会提高很多。
如果你们方便的话。

**Comment by fangrenfu** [comment]
同样期待PDF版本

**Comment by ShusenTang** [comment]
[《动手学深度学习》(PyTorch版)网页版](http://shusentang.github.io/Dive-into-DL-PyTorch/)现已推出，公式完美渲染，感谢持续关注
