### ISSUE TITLE
3.3.3节代码问题

### ISSUE THREAD

**Issue by amituofo1996** [ShusenTang/Dive-into-DL-PyTorch#142]
**bug描述**
缺少关键代码
import torch.nn as nn
描述一下你遇到的bug, 例如报错位置、报错信息（重要, 可以直接截个图）等
![3 3节代码问题](https://user-images.githubusercontent.com/49180284/85817144-c4f07f00-b79f-11ea-9d8d-3f038d5b294f.PNG)

**版本信息**
pytorch: 1.5.1
torchvision: 0.6.1
torchtext: 如上
...

**Comment by 1053399472** [comment]
把你的import前面的#去了
