### ISSUE TITLE
数学公式无法显示

### ISSUE THREAD

**Issue by bugmaker2** [ShusenTang/Dive-into-DL-PyTorch#158]
**bug描述**
markdown文档所有数学公式无法显示

**版本信息**

**Comment by WTangsanW** [comment]
我也是

**Comment by wangzhongqing** [comment]
这是来自QQ邮箱的假期自动回复邮件。
王中情：
您好，已收到您的邮件，我会尽快给您回复。谢谢您的邮件！祝您生活愉快！
