### ISSUE TITLE
公式一个都看不到，想看又看不下去，真是难受

### ISSUE THREAD

**Issue by Yufengevan** [ShusenTang/Dive-into-DL-PyTorch#16]

**Comment by sunjinr** [comment]
作者不是给chrome的解决方案了吗？为什么还有底气吐槽

**Comment by Yufengevan** [comment]
> 作者不是给chrome的解决方案了吗？为什么还有底气吐槽

我下载了一个markdown软件，打开还是这样。底气是什么意思？

**Comment by sunjinr** [comment]
那为什么不寻求别的解决方案？比如作者提到的 chrome 和 jupyter notebook

**Comment by Yufengevan** [comment]
> 那为什么不寻求别的解决方案？比如作者提到的 chrome 和 jupyter notebook

也寻求了，还是没有解决。所以才比较难受。

**Comment by caoshuai619** [comment]
作者说了啊，下载Typora,在偏好设置选择inline math
