### ISSUE TITLE
Other: 域名过期

### ISSUE THREAD

**Issue by Dustella** [ShusenTang/Dive-into-DL-PyTorch#190]
**bug描述**

2024 年 10 月 7 日， https://tangshusen.me/ 域名过期，文章内容无法访问。

![image](https://github.com/user-attachments/assets/e930db7b-c7c9-4a27-ad29-fd4b9423ee92)

可以使用 Github Pages 自带的域名，只需要注意处理 baseurl 并且关掉 Custom Domain. 

**版本信息**
pytorch: N/A
torchvision: N/A
torchtext: N/A

**Comment by ShusenTang** [comment]
已经续上了
