### ISSUE TITLE
域名过期

### ISSUE THREAD

**Issue by XinDaQie** [ShusenTang/Dive-into-DL-PyTorch#191]
域名过期的解决方案可以通过 GitHub Pages 的默认域名来解决，下面是操作步骤：

### 1. **关闭 Custom Domain**

如果你之前设置了自定义域名（比如 `https://tangshusen.me/`），你需要关闭这个设置：

- 在 GitHub 仓库的 **Settings** 页面，找到 **GitHub Pages** 配置部分。
- 确保 **Custom Domain** 一栏为空，然后保存。
- GitHub Pages 会为你生成一个类似 `https://username.github.io/repository-name/` 的默认域名。

### 2. **修改 `baseurl`**

如果你的网站在根目录下托管，可以直接使用 `baseurl: ""`。如果它托管在子目录下，你需要设置正确的 `baseurl`。例如，如果你的 GitHub Pages 域名是 `https://username.github.io/repository-name/`，那么你的 `_config.yml` 文件中需要如下设置：

```yaml
baseurl: "/repository-name"  # 设置为你的仓库名
```

### 3. **确保页面链接正常**

你可能需要在页面的链接中使用 `{{ site.baseurl }}` 来生成正确的链接，以确保所有相对路径能够正确解析。例如：

```html
<a href="{{ site.baseurl }}/about/">About</a>
```

这样即使你更改了域名，链接也会自动适应新的 `baseurl`。

完成这些步骤后，你的页面将通过 GitHub Pages 默认域名正常访问。

**Comment by HUA-X-dragon** [comment]
可以说得详细点嘛，我找不到_config.yml文件，不知道在设置baseurl

**Comment by ShusenTang** [comment]
之前的过期了，刚刚已经续上了
