### ISSUE TITLE
关于第九章的一些疑问

### ISSUE THREAD

**Issue by Ricinix** [ShusenTang/Dive-into-DL-PyTorch#2]
在mxnet原作9.4中，涉及到了MultiBoxTarget、MultiBoxPrior、MultiBoxDetection这几个库函数。我想探讨下在pytorch中相对应的库函数是什么呢？还是说只能自己手动实现这些功能？

**Comment by ShusenTang** [comment]
你好，最近有点忙所以第九章还没怎么更新，我尽快更新，敬请关注。

**Comment by ShusenTang** [comment]
> 在mxnet原作9.4中，涉及到了MultiBoxTarget、MultiBoxPrior、MultiBoxDetection这几个库函数。我想探讨下在pytorch中相对应的库函数是什么呢？还是说只能自己手动实现这些功能？

9.4节已更新，这三个函数PyTorch都没有现成的，所以我对其进行了简单实现。
