### ISSUE TITLE
我重新制作了PDF版本，修复了公式和图片问题，希望推上主链

### ISSUE THREAD

**Issue by chenyang1999** [ShusenTang/Dive-into-DL-PyTorch#21]

**Comment by yongboy** [comment]
很赞！

以下为个人建议：

1. 在本仓库没有完善之前，不建议把依赖于当前提交生成的PDF放入仓库内，原因如下：
    - 项目没有完善之前的所构建PDF文件变动也会频繁
    - PDF文件太大，检入/检出太耗费网络流量
2. 建议各位把PDF文件放入百度等网盘内，或个人网站中，然后把链接和对应提交Hash/Tag说明放入项目WIKI中
     - 有能力的同学，建议根据本项目master变动自动生成最新的PDF文件，并同时自动上传到网上位置，这样可保证任何时间点下载都是最新的PDF文档
3. 建议把生成PDF的脚本文件完善一下，比如保存在 tools 目录下，申请Pull Request

加油！

**Comment by chenyang1999** [comment]
感谢老师给出的宝贵意见.
1. 我制作的过程并不是直接使用脚本,使用的是 typora 进行排版,近期会尝试制作一键生成脚本,方便各位自行编译.
2. 这里也放出 demo 版,方便一部分有需要的朋友预览:
https://github.com/OUCMachineLearning/OUCML/blob/master/BOOK/Dive-into-DL-PyTorch.pdf

**Comment by gggamemaster** [comment]
您好，您知道怎么导入d2lzh_pytorch吗

**Comment by yongboy** [comment]
@gggamemaster 
原档中有啊
```python
sys.path.append("..") # 为了导入上层目录的d2lzh_pytorch
import d2lzh_pytorch as d2l
```

**Comment by ShusenTang** [comment]
[《动手学深度学习》(PyTorch版)网页版](http://shusentang.github.io/Dive-into-DL-PyTorch/)现已推出，公式完美渲染，感谢持续关注

**Comment by deepmeng** [comment]
PDF还是容易做笔记，学习。请问楼主如何制作PDF文件@chenyang1999

**Comment by chenyang1999** [comment]
> PDF还是容易做笔记，学习。请问楼主如何制作PDF文件@ chenyang1999
就是把 markdown 写到一起,用 pandoc 转换的(typora 也行)

**Comment by deepmeng** [comment]
> > PDF还是容易做笔记，学习。请问楼主如何制作PDF文件@ chenyang1999

>  就是把 markdown 写到一起,用 pandoc 转换的(typora 也行)

收到 谢谢！
