### ISSUE TITLE
如果使用pytorch1.1.0版本，章节3.7和3.10的代码会无法运行

### ISSUE THREAD

**Issue by cGy147** [ShusenTang/Dive-into-DL-PyTorch#26]

**Comment by gggamemaster** [comment]
解决了吗？我今天运行3.7代码也不行

**Comment by ShusenTang** [comment]
刚刚用1.2.0测试了3.7是没有任何问题的，请把报错信息贴出来重新提issue

**Comment by cGy147** [comment]
RuntimeError                              Traceback (most recent call last)
<ipython-input-9-4f5dfa17aa83> in <module>
      1 num_epochs = 5
----> 2 d2l.train_ch3(net, train_iter, test_iter, loss, num_epochs, batch_size, None, None, optimizer)

D:\cgy-learn\booktest\Dive in deeplearning\code\d2lzh_pytorch\utils.py in train_ch3(net, train_iter, test_iter, loss, num_epochs, batch_size, params, lr, optimizer)
    140             train_acc_sum += (y_hat.argmax(dim=1) == y).sum().item()
    141             n += y.shape[0]
--> 142         test_acc = evaluate_accuracy(test_iter, net)
    143         print('epoch %d, loss %.4f, train acc %.3f, test acc %.3f'
    144               % (epoch + 1, train_l_sum / n, train_acc_sum / n, test_acc))

D:\cgy-learn\booktest\Dive in deeplearning\code\d2lzh_pytorch\utils.py in evaluate_accuracy(data_iter, net, device)
    212             if isinstance(net, torch.nn.Module):
    213                 net.eval() # 评估模式, 这会关闭dropout
--> 214                 acc_sum += (net(X.to(device)).argmax(dim=1) == y.to(device)).float().sum().cpu().item()
    215                 net.train() # 改回训练模式
    216             else: # 自定义的模型, 3.13节之后不会用到, 不考虑GPU

~\Anaconda3\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    491             result = self._slow_forward(*input, **kwargs)
    492         else:
--> 493             result = self.forward(*input, **kwargs)
    494         for hook in self._forward_hooks.values():
    495             hook_result = hook(self, input, result)

~\Anaconda3\lib\site-packages\torch\nn\modules\container.py in forward(self, input)
     90     def forward(self, input):
     91         for module in self._modules.values():
---> 92             input = module(input)
     93         return input
     94 

~\Anaconda3\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    491             result = self._slow_forward(*input, **kwargs)
    492         else:
--> 493             result = self.forward(*input, **kwargs)
    494         for hook in self._forward_hooks.values():
    495             hook_result = hook(self, input, result)

~\Anaconda3\lib\site-packages\torch\nn\modules\linear.py in forward(self, input)
     90     @weak_script_method
     91     def forward(self, input):
---> 92         return F.linear(input, self.weight, self.bias)
     93 
     94     def extra_repr(self):

~\Anaconda3\lib\site-packages\torch\nn\functional.py in linear(input, weight, bias)
   1404     if input.dim() == 2 and bias is not None:
   1405         # fused op is marginally faster
-> 1406         ret = torch.addmm(bias, input, weight.t())
   1407     else:
   1408         output = input.matmul(weight.t())

RuntimeError: Expected object of backend CPU but got backend CUDA for argument #4 'mat1'


注释掉utils.py的evaluate_accuracy中的语句：
**device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')):**
可以解决该报错
