### ISSUE TITLE
在本地上运动我该怎么导入d2lzh_pytorch 

### ISSUE THREAD

**Issue by gggamemaster** [ShusenTang/Dive-into-DL-PyTorch#29]
求解

**Comment by GSwithAI** [comment]
同问

**Comment by ShusenTang** [comment]
基本上每节都有例子呀，如下图
![image](https://user-images.githubusercontent.com/16498688/66754996-1be44b80-eed2-11e9-8877-38e216d690c0.png)
即用`sys.path.append(PATH) `把你存放d2lzh_pytorch的路径加进来，然后就可以正常导入了

**Comment by GSwithAI** [comment]
> 基本上每节都有例子呀，如下图
> ![image](https://user-images.githubusercontent.com/16498688/66754996-1be44b80-eed2-11e9-8877-38e216d690c0.png)
> 即用`sys.path.append(PATH) `把你存放d2lzh_pytorch的路径加进来，然后就可以正常导入了

d2lzh_pytorch这个包在哪里下载呢

**Comment by ShusenTang** [comment]
> > 基本上每节都有例子呀，如下图
> > ![image](https://user-images.githubusercontent.com/16498688/66754996-1be44b80-eed2-11e9-8877-38e216d690c0.png)
> > 即用`sys.path.append(PATH) `把你存放d2lzh_pytorch的路径加进来，然后就可以正常导入了
> 
> d2lzh_pytorch这个包在哪里下载呢

就在code文件夹里呀

**Comment by gggamemaster** [comment]
我把这个包下了，在conda虚拟环境安装不成功。

**Comment by ShusenTang** [comment]
> 我把这个包下了，在conda虚拟环境安装不成功。

不用安装（也安装不上），直接用就是，代码就在code文件夹里

**Comment by gggamemaster** [comment]
我把utils.py下载下来。导入我的jupyter notebook中,在运行3.7代码的时候出现了bug，我的pytorch是1.3

**Comment by ShusenTang** [comment]
> 我把utils.py下载下来。导入我的jupyter notebook中,在运行3.7代码的时候出现了bug，我的pytorch是1.3

报错信息贴出来看看

**Comment by gggamemaster** [comment]
RuntimeError                              Traceback (most recent call last)
<ipython-input-17-4f5dfa17aa83> in <module>
      1 num_epochs = 5
----> 2 d2l.train_ch3(net, train_iter, test_iter, loss, num_epochs, batch_size, None, None, optimizer)

~\utils.py in train_ch3(net, train_iter, test_iter, loss, num_epochs, batch_size, params, lr, optimizer)
    140             train_acc_sum += (y_hat.argmax(dim=1) == y).sum().item()
    141             n += y.shape[0]
--> 142         test_acc = evaluate_accuracy(test_iter, net)
    143         print('epoch %d, loss %.4f, train acc %.3f, test acc %.3f'
    144               % (epoch + 1, train_l_sum / n, train_acc_sum / n, test_acc))

~\utils.py in evaluate_accuracy(data_iter, net, device)
    212             if isinstance(net, torch.nn.Module):
    213                 net.eval() # 评估模式, 这会关闭dropout
--> 214                 acc_sum += (net(X.to(device)).argmax(dim=1) == y.to(device)).float().sum().cpu().item()
    215                 net.train() # 改回训练模式
    216             else: # 自定义的模型, 3.13节之后不会用到, 不考虑GPU

D:\anaconda\envs\PyTorch\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    539             result = self._slow_forward(*input, **kwargs)
    540         else:
--> 541             result = self.forward(*input, **kwargs)
    542         for hook in self._forward_hooks.values():
    543             hook_result = hook(self, input, result)

D:\anaconda\envs\PyTorch\lib\site-packages\torch\nn\modules\container.py in forward(self, input)
     90     def forward(self, input):
     91         for module in self._modules.values():
---> 92             input = module(input)
     93         return input
     94 

D:\anaconda\envs\PyTorch\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    539             result = self._slow_forward(*input, **kwargs)
    540         else:
--> 541             result = self.forward(*input, **kwargs)
    542         for hook in self._forward_hooks.values():
    543             hook_result = hook(self, input, result)

D:\anaconda\envs\PyTorch\lib\site-packages\torch\nn\modules\linear.py in forward(self, input)
     85 
     86     def forward(self, input):
---> 87         return F.linear(input, self.weight, self.bias)
     88 
     89     def extra_repr(self):

D:\anaconda\envs\PyTorch\lib\site-packages\torch\nn\functional.py in linear(input, weight, bias)
   1368     if input.dim() == 2 and bias is not None:
   1369         # fused op is marginally faster
-> 1370         ret = torch.addmm(bias, input, weight.t())
   1371     else:
   1372         output = input.matmul(weight.t())

RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _th_addmm

**Comment by gggamemaster** [comment]
完整的代码
import torch
from torch import nn
from torch.nn import init
import numpy as np
import sys
sys.path.append("..") 
import utils as d2l

print(torch.__version__)

batch_size = 256
train_iter, test_iter = d2l.load_data_fashion_mnist(batch_size)

num_inputs = 784
num_outputs = 10

# class LinearNet(nn.Module):
#     def __init__(self, num_inputs, num_outputs):
#         super(LinearNet, self).__init__()
#         self.linear = nn.Linear(num_inputs, num_outputs)
#     def forward(self, x): # x shape: (batch, 1, 28, 28)
#         y = self.linear(x.view(x.shape[0], -1))
#         return y
    
# net = LinearNet(num_inputs, num_outputs)

class FlattenLayer(nn.Module):
    def __init__(self):
        super(FlattenLayer, self).__init__()
    def forward(self, x): # x shape: (batch, *, *, ...)
        return x.view(x.shape[0], -1)

from collections import OrderedDict
net = nn.Sequential(
        # FlattenLayer(),
        # nn.Linear(num_inputs, num_outputs)
        OrderedDict([
          ('flatten', FlattenLayer()),
          ('linear', nn.Linear(num_inputs, num_outputs))])
        )

init.normal_(net.linear.weight, mean=0, std=0.01)
init.constant_(net.linear.bias, val=0)
loss = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(net.parameters(), lr=0.1)
num_epochs = 5
d2l.train_ch3(net, train_iter, test_iter, loss, num_epochs, batch_size, None, None, optimizer)

**Comment by ShusenTang** [comment]
> RuntimeError Traceback (most recent call last)
> in
> 1 num_epochs = 5
> ----> 2 d2l.train_ch3(net, train_iter, test_iter, loss, num_epochs, batch_size, None, None, optimizer)
> 
> ~\utils.py in train_ch3(net, train_iter, test_iter, loss, num_epochs, batch_size, params, lr, optimizer)
> 140 train_acc_sum += (y_hat.argmax(dim=1) == y).sum().item()
> 141 n += y.shape[0]
> --> 142 test_acc = evaluate_accuracy(test_iter, net)
> 143 print('epoch %d, loss %.4f, train acc %.3f, test acc %.3f'
> 144 % (epoch + 1, train_l_sum / n, train_acc_sum / n, test_acc))
> 
> ~\utils.py in evaluate_accuracy(data_iter, net, device)
> 212 if isinstance(net, torch.nn.Module):
> 213 net.eval() # 评估模式, 这会关闭dropout
> --> 214 acc_sum += (net(X.to(device)).argmax(dim=1) == y.to(device)).float().sum().cpu().item()
> 215 net.train() # 改回训练模式
> 216 else: # 自定义的模型, 3.13节之后不会用到, 不考虑GPU
> 
> D:\anaconda\envs\PyTorch\lib\site-packages\torch\nn\modules\module.py in **call**(self, *input, **kwargs)
> 539 result = self._slow_forward(*input, **kwargs)
> 540 else:
> --> 541 result = self.forward(*input, **kwargs)
> 542 for hook in self._forward_hooks.values():
> 543 hook_result = hook(self, input, result)
> 
> D:\anaconda\envs\PyTorch\lib\site-packages\torch\nn\modules\container.py in forward(self, input)
> 90 def forward(self, input):
> 91 for module in self._modules.values():
> ---> 92 input = module(input)
> 93 return input
> 94
> 
> D:\anaconda\envs\PyTorch\lib\site-packages\torch\nn\modules\module.py in **call**(self, *input, **kwargs)
> 539 result = self._slow_forward(*input, **kwargs)
> 540 else:
> --> 541 result = self.forward(*input, **kwargs)
> 542 for hook in self._forward_hooks.values():
> 543 hook_result = hook(self, input, result)
> 
> D:\anaconda\envs\PyTorch\lib\site-packages\torch\nn\modules\linear.py in forward(self, input)
> 85
> 86 def forward(self, input):
> ---> 87 return F.linear(input, self.weight, self.bias)
> 88
> 89 def extra_repr(self):
> 
> D:\anaconda\envs\PyTorch\lib\site-packages\torch\nn\functional.py in linear(input, weight, bias)
> 1368 if input.dim() == 2 and bias is not None:
> 1369 # fused op is marginally faster
> -> 1370 ret = torch.addmm(bias, input, weight.t())
> 1371 else:
> 1372 output = input.matmul(weight.t())
> 
> RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _th_addmm

报错信息说得很清楚啦就是device不匹配，应该是你的机器有GPU，你把utils.py里面关于evaluate_accuracy的前几行改成以下应该就可以了:
``` python
# ############################ 5.5 #########################
def evaluate_accuracy(data_iter, net, device=None):
    if device is None:
        device = list(net.parameters())[0].device # net的device
    acc_sum, n = 0.0, 0
```

**Comment by gggamemaster** [comment]
谢谢您，经过修改以后已经可以运行了

**Comment by gggamemaster** [comment]
代码在实现多层感知机的时候出bug了，bug是由于修改处的代码引起的。
d2l.train_ch3(net, train_iter, test_iter, loss, num_epochs,batch_size, params, lr)
AttributeError                            Traceback (most recent call last)
<ipython-input-17-98cb0edb818b> in <module>
----> 1 d2l.train_ch3(net, train_iter, test_iter, loss, num_epochs,batch_size, params, lr)

~\utils.py in train_ch3(net, train_iter, test_iter, loss, num_epochs, batch_size, params, lr, optimizer)
    140             train_acc_sum += (y_hat.argmax(dim=1) == y).sum().item()
    141             n += y.shape[0]
--> 142         test_acc = evaluate_accuracy(test_iter, net)
    143         print('epoch %d, loss %.4f, train acc %.3f, test acc %.3f'
    144               % (epoch + 1, train_l_sum / n, train_acc_sum / n, test_acc))

~\utils.py in evaluate_accuracy(data_iter, net, device)
    207 def evaluate_accuracy(data_iter, net, device=None):
    208     if device is None:
--> 209         device = list(net.parameters())[0].device # net的device
    210     acc_sum, n = 0.0, 0
    211     with torch.no_grad():

AttributeError: 'function' object has no attribute 'parameters'

**Comment by ShusenTang** [comment]
> 代码在实现多层感知机的时候出bug了，bug是由于修改处的代码引起的。
> d2l.train_ch3(net, train_iter, test_iter, loss, num_epochs,batch_size, params, lr)
> AttributeError Traceback (most recent call last)
> in
> ----> 1 d2l.train_ch3(net, train_iter, test_iter, loss, num_epochs,batch_size, params, lr)
> 
> ~\utils.py in train_ch3(net, train_iter, test_iter, loss, num_epochs, batch_size, params, lr, optimizer)
> 140 train_acc_sum += (y_hat.argmax(dim=1) == y).sum().item()
> 141 n += y.shape[0]
> --> 142 test_acc = evaluate_accuracy(test_iter, net)
> 143 print('epoch %d, loss %.4f, train acc %.3f, test acc %.3f'
> 144 % (epoch + 1, train_l_sum / n, train_acc_sum / n, test_acc))
> 
> ~\utils.py in evaluate_accuracy(data_iter, net, device)
> 207 def evaluate_accuracy(data_iter, net, device=None):
> 208 if device is None:
> --> 209 device = list(net.parameters())[0].device # net的device
> 210 acc_sum, n = 0.0, 0
> 211 with torch.no_grad():
> 
> AttributeError: 'function' object has no attribute 'parameters'

这里是因为传入net不是一个PyTorch模型而是我们自己写的一个函数，所以没有parameter这个是属性，所以我任务把utils里面的evaluate_accuracy的第一行
``` python
if device is None:
```
改成
``` python
if device is None and isinstance(net, torch.nn.Module):
```
应该就可以了。

**Comment by TengFeiHan0** [comment]
我导入路径了为什么还不行呢？
`sys.path.append("/home/tengfeihan/Dive-into-DL-PyTorch/code/d2lzh_pytorch")` 新手不太会 @ShusenTang

**Comment by gggamemaster** [comment]
把里面的py文件下载下来直接用就行



------------------ 原始邮件 ------------------
发件人: "Tengfei han"<notifications@github.com>; 
发送时间: 2019年10月16日(星期三) 下午4:02
收件人: "ShusenTang/Dive-into-DL-PyTorch"<Dive-into-DL-PyTorch@noreply.github.com>; 
抄送: "553270311"<553270311@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ShusenTang/Dive-into-DL-PyTorch] 在本地上运动我该怎么导入d2lzh_pytorch  (#29)




我导入路径了为什么还不行呢？
 sys.path.append("/home/tengfeihan/Dive-into-DL-PyTorch/code/d2lzh_pytorch") 新手不太会 @ShusenTang

**Comment by alljie-cool** [comment]
![image](https://user-images.githubusercontent.com/59225738/71478192-46834680-2829-11ea-8da5-b1c2985bbad9.png)

**Comment by ShusenTang** [comment]
@alljie-cool 首先`sys.append.append("..")`是为了把父目录加入工作区（因为d2l_pytorch在父目录），我不知道为什么在你这不行。我提供一个解决方案，因为d2l_pytorch所有代码都在`d2l_pytorch/utils.y`中，所以你可以把这个`utils.py`放入代码目录里，这样就可以在代码中`import utils as d2l`，遇到问题可以用`python 导入py文件`作关键词google

**Comment by yuhuanshui** [comment]
您好！小白请教。。在colab中如何导入d2lzh_pytorch?谢谢啦！

**Comment by yuhuanshui** [comment]
@ShusenTang 您好！小白请教。。。在colab中如何导入d2lzh_pytorch?谢谢啦

**Comment by DayBright-David** [comment]
<img width="719" alt="截屏2020-05-13 下午1 41 56" src="https://user-images.githubusercontent.com/59006279/81775493-85d3da80-951f-11ea-9885-7fec465538d6.png">

**Comment by StevenJokes** [comment]
@DayBright-David 
`!pip install d2lzh_pytorch`
