### ISSUE TITLE
3.2.7训练模型 代码bug

### ISSUE THREAD

**Issue by longzhongba** [ShusenTang/Dive-into-DL-PyTorch#31]
**bug描述**
3.2.7训练模型 代码运行报错

RuntimeError                              Traceback (most recent call last)
<ipython-input-36-7b29f0453e1a> in <module>
      8     # 和y分别是小批量样本的特征和标签
      9     for X, y in data_iter(batch_size, features, labels):
---> 10         l = loss(net(X, w, b), y).sum()  # l是有关小批量X和y的损失
     11         l.backward()  # 小批量的损失对模型参数求梯度
     12         sgd([w, b], lr, batch_size)  # 使用小批量随机梯度下降迭代模型参数

<ipython-input-33-7aefd52381cf> in linreg(X, w, b)
      1 def linreg(X, w, b):  # 本函数已保存在d2lzh_pytorch包中方便以后使用
----> 2     return torch.mm(X, w) + b

RuntimeError: Expected object of scalar type Double but got scalar type Float for argument #2 'mat2'

将3.2.3初始化参数部分类型改为double或float64可运行

**版本信息**
pytorch:1.2.0
torchvision:0.4.0
torchtext:?
安装指令是
conda install pytorch torchvision cudatoolkit=10.0
使用清华镜像

**Comment by ty258635370** [comment]
把前面生成模型的features和labels+= 转换成float32格式完美解决
######float64和32报错
num_inputs = 2
num_examples = 1000
true_w = [2, -3.4]
true_b = 4.2
features = torch.from_numpy(np.random.normal(0, 1, (num_examples, num_inputs)))
features = features.to(torch.float32)
labels = true_w[0] * features[:, 0] + true_w[1] * features[:, 1] + true_b
dd = torch.from_numpy(np.random.normal(0, 0.01, size=labels.size()))
dd = dd.to(torch.float32)
labels += dd
features[0],labels[0]
#####或者是
num_inputs = 2
num_examples = 1000
true_w = [2, -3.4]
true_b = 4.2
features = torch.randn(num_examples, num_inputs)
labels = true_w[0] * features[:, 0] + true_w[1] * features[:, 1] + true_b
labels += torch.tensor(np.random.normal(0, 0.01, size=labels.size()), dtype=torch.float)
