### ISSUE TITLE
【建议：】可通过gitbook搭建在线书籍

### ISSUE THREAD

**Issue by zooltd** [ShusenTang/Dive-into-DL-PyTorch#32]
示例：https://zooltd.gitbook.io/dive-into-deep-learning-demo/

**Comment by zooltd** [comment]
（会对原有项目的目录结构有改动），建议另开一个仓库

**Comment by ShusenTang** [comment]
嗯，我确实是有将其转成在线文档的打算，但是我之前了解到相比docsify，gitbook每次都需要build，而且还会产生很多html文件，所以打算用docsify，不知道最后效果怎么样。#27
