### ISSUE TITLE
4.2.2 未针对PyTorch修改

### ISSUE THREAD

**Issue by zooltd** [ShusenTang/Dive-into-DL-PyTorch#40]

**Comment by zooltd** [comment]
原文："如果只想对某个特定参数进行初始化，我们可以调用Parameter类的initialize函数，它与Block类提供的initialize函数的使用方法一致。"
PyTorch内置的参数初始化函数似乎只在torch.nn.init中

**Comment by ShusenTang** [comment]
> 原文：
> "如果只想对某个特定参数进行初始化，我们可以调用Parameter类的initialize函数，它与Block类提供的initialize函数的使用方法一致。"
> 可修改为：
> 如果只想对某个特定参数进行初始化，除使用torch.nn.init库中提供的参数初始化函数外，我们还可以调用Tensor类的填充函数（如normal_(...)，random_(...)等）。

4.2.3节讲了如何自定义初始化方法，所以我直接把这段话删了
