### ISSUE TITLE
建议增加CI/CD

### ISSUE THREAD

**Issue by forest0** [ShusenTang/Dive-into-DL-PyTorch#43]
可以在CI里边做静态网页生成和pdf生成，在CD里边部署网页，这样就可以只专注于markdown及图片的修改。

看了下，作者似乎是想放到github pages上，[travis-ci 也有相应的支持](https://docs.travis-ci.com/user/deployment/pages/)。

**Comment by ShusenTang** [comment]
[《动手学深度学习》(PyTorch版)网页版](http://shusentang.github.io/Dive-into-DL-PyTorch/)现已推出，公式完美渲染，感谢持续关注

**Comment by forest0** [comment]
这样是解决了网页的问题，但估计有人也有pdf的需求，后续有时间的话可以考虑下。

**Comment by ShusenTang** [comment]
> 这样是解决了网页的问题，但估计有人也有pdf的需求，后续有时间的话可以考虑下。

等把全部章节更新完毕了，应该会考虑出一个pdf
