### ISSUE TITLE
3.16节 kaggle_house的一个小错误

### ISSUE THREAD

**Issue by CaiyuZhang** [ShusenTang/Dive-into-DL-PyTorch#46]
**bug描述**
在预处理数据代码中，原文为
all_features[numeric_features] = all_features[numeric_features].fillna(0) 
最终输出应为 all_features.shape = (2919, 331)
而在您编写的代码中，此句变为
all_features = all_features.fillna(0)
最终输出为all_features.shape = (2919, 354)，
初次接触pandas，不知这个是您的疏忽还是由于我对代码的理解不充分，望解答，十分感谢。

**版本信息**
pytorch:
torchvision:
torchtext:
...

**Comment by huiget** [comment]
同意你的看法。
`In [34]: df = pd.DataFrame({'a': [1, 2, None, 3], 'b': ['a', 'b', None, '0']})

In [35]: pd.get_dummies(df, dummy_na=True)
Out[35]:
     a  b_0  b_a  b_b  b_nan
0  1.0    0    1    0      0
1  2.0    0    0    1      0
2  NaN    0    0    0      1
3  3.0    1    0    0      0

In [36]: df_new = df.fillna(0)

In [37]: pd.get_dummies(df_new, dummy_na=True)
Out[37]:
     a  b_0  b_0  b_a  b_b  b_nan
0  1.0    0    0    1    0      0
1  2.0    0    0    0    1      0
2  0.0    1    0    0    0      0
3  3.0    0    1    0    0      0

`

**Comment by ShusenTang** [comment]
感谢提醒，已更正
