### ISSUE TITLE
The pictures of formulas in this book are not visible! 

### ISSUE THREAD

**Issue by landwinner** [ShusenTang/Dive-into-DL-PyTorch#48]
![1571822380(1)](https://user-images.githubusercontent.com/35477838/67378148-62fccb80-f5b9-11e9-976a-63d9ed3e5194.jpg)

The pictures of formulas in this book are not visible! It's very inconvenient for readers to read.

**Comment by ShusenTang** [comment]
That is because github native markdown doesn't support latex formula rendering. You can read the [web docs](http://tangshusen.me/Dive-into-DL-PyTorch) directly, I mentioned it in README.

**Comment by landwinner** [comment]
Mr.Tang,thank you!
