### ISSUE TITLE
3.2节里的线性回归w和b的初始化时数据为float32类型，导致后面计算矩阵相乘错误

### ISSUE THREAD

**Issue by xiaoDragon** [ShusenTang/Dive-into-DL-PyTorch#54]
python vision:py3.7
torchvision：0.4.0

3.2节里的线性回归w和b的初始化时数据为float32类型，导致后面计算矩阵相乘错误
我试着打印出features时，发现数据类型是float64类型的，而后面的w和b均是float32类型。训练的时候使用torch.mm做矩阵，这个函数需要统一传进来的三个参数类型，所以在初始化w和b时需要将其设置为torch.float64类型才可以。

验证如下：
![LUN_JV9XPNS9 1){_300 $8](https://user-images.githubusercontent.com/26972500/67628644-114b8e00-f8a4-11e9-9d5a-968304371382.png)
![error](https://user-images.githubusercontent.com/26972500/67628633-dd706880-f8a3-11e9-83f0-2d991add287f.png)

修改后的结果如下：
![1572143875(1)](https://user-images.githubusercontent.com/26972500/67628747-e95d2a00-f8a5-11e9-8ee3-06eef888a646.jpg)
![4(V6YZBV@`QXJ%E6OD}0LVI](https://user-images.githubusercontent.com/26972500/67628752-f8dc7300-f8a5-11e9-8caa-3d1cd6299a13.png)

**Comment by ShusenTang** [comment]
已更正: 将所有都统一成float32
