### ISSUE TITLE
公式都是laTex格式，没有被转换

### ISSUE THREAD

**Issue by DemonsRhythm** [ShusenTang/Dive-into-DL-PyTorch#6]

**Comment by jianpingbadao** [comment]
Markdown是支持LaTex格式的公式的，只不过需要安装插件或者进行相关配置。比如说Visual studio code, 可以安装markdown的扩展，搜出来的第一个(Markdown all in one)就可以了。再或者说用Typora，可以在软件的偏好设置中，勾选inline Math即可。

**Comment by ChanSiYuan** [comment]
可以在google浏览器上安装Latex all the thing插件，看着基本都对了

**Comment by cloud0435** [comment]
其实这个不影响，直接复制到jupyter notebook中，单元格选择markdown，直接出来公式了。

**Comment by yongboy** [comment]
针对此问题，我已提交一个PR #27。

当项目检出到本地后，在Mac/Linux等终端下（不支持Windows），进入项目目录，输入 `make wwwdocs`，回车，然后在在chrome等现代浏览器内访问：`http://localhost:3000` 访问文档库的形式自由访问，Latex参数同时会被自动解析。

```bash
# make wwwdocs
bash script/prepare_wwwdocs.sh
本脚本将自动创建 .wwwdocs 目录
初始化项目依赖时将使用 docsify 工具自动生成本地文档web访问文档
本web文档为绿色创建，不会对现有项目产生副作用！不会产生产生git需要提交文件！
请放心食用 :))
根据项目README.md自动生成目录文件 ......
根据项目根目录下README.md以及docs/README.md合并生成项目所需${docs}导航 ......
生成 docsify 所需入口文件......
为各章节markdown文件以及图片建立软连接 ......
启动web server，稍后请在浏览器中打开：http://localhost:3000 ，即可访问 ......

Serving /Users/nieyong/ai/book/Dive-into-DL-PyTorch/.wwwdocs now.
Listening at http://localhost:3000
```

效果截图如下:

![](https://i.loli.net/2019/10/11/QTiqz5j8K1YsxmN.jpg)
