### ISSUE TITLE
关于第五章的函数 d2l.train_ch5 

### ISSUE THREAD

**Issue by wangrongqian2019** [ShusenTang/Dive-into-DL-PyTorch#60]
**bug描述**
关于第五章的函数 d2l.train_ch5 中的batch_count=0难道不应该写在循环内部吗，请问老师您为什么把问题关掉了，不太理解，所以再来询问一下。

**版本信息**
pytorch:
torchvision:
torchtext:
...

**Comment by ShusenTang** [comment]
> **bug描述**
> 关于第五章的函数 d2l.train_ch5 中的batch_count=0难道不应该写在循环内部吗，请问老师您为什么把问题关掉了，不太理解，所以再来询问一下。
> 
> **版本信息**
> pytorch:
> torchvision:
> torchtext:
> ...

嗯对的，刚刚看了一下确实是应该放里面。我明天改一下，谢谢提醒
