### ISSUE TITLE
rnn-pytorch中循环神经网络那张图下面的输出形状是否有误?

### ISSUE THREAD

**Issue by zzuruichao** [ShusenTang/Dive-into-DL-PyTorch#65]
![1574817355(1)](https://user-images.githubusercontent.com/58239273/69685259-c6b56f80-10f6-11ea-8f0c-baa7df7594c5.jpg)
输出形状是否应该为（时间步数，批量大小，隐藏层单元个数）。

**Comment by ShusenTang** [comment]
嗯对的，打错了，感谢提醒
