### ISSUE TITLE
5.10使用pandoc转为pdf报错

### ISSUE THREAD

**Issue by tsrjzq** [ShusenTang/Dive-into-DL-PyTorch#68]
**bug描述**
chapter05中的5.10_batch-norm.md文件，转为pdf的时候报错。信息如下：

Error producing PDF.
! Missing { inserted.
<to be read again> 
                   \__um_group_begin: 
l.135 \[\boldsymbol{\mu}_\mathcal

对markdown和LaTeX的语法不熟，不知道是什么原因？其他的章节都没问题。

谢谢
**版本信息**
pytorch:
torchvision:
torchtext:
...

**Comment by ShusenTang** [comment]
转成pdf的话，不是我这边的锅呀，报错信息不是说了嘛，Missing { inserted.，应该是公式里面的大括号没被正确识别到

**Comment by tsrjzq** [comment]
报错信息只是那么说的，事实上肯定不是这个问题。但是究竟是什么问题，一时半会儿看不出。我的意思是您如果有空就看一下，没空就算了，确实不是您的锅，呵呵。

**Comment by ShusenTang** [comment]
> 报错信息只是那么说的，事实上肯定不是这个问题。但是究竟是什么问题，一时半会儿看不出。我的意思是您如果有空就看一下，没空就算了，确实不是您的锅，呵呵。

应该就是公式里面的大括号没正确识别到。你可以试试把那大段公式删了，再转换看有没有问题，没问题的话就是那堆公式没被pandoc正确解析
