### ISSUE TITLE
AttributeError: module 'd2lzh_pytorch' has no attribute 'load_data_fashion_mnist'

### ISSUE THREAD

**Issue by fzcz** [ShusenTang/Dive-into-DL-PyTorch#69]
**bug描述**
描述一下你遇到的bug, 例如报错位置、报错信息（重要, 可以直接截个图）等

**版本信息**
pytorch:
torchvision:
torchtext:
...

**Comment by ShusenTang** [comment]
怎么会没有呢，load_data_fashion_mnist这个函数在d2lzh_pytorch/utils.py下面呀

**Comment by Thoye** [comment]
> **bug描述**
> 描述一下你遇到的bug, 例如报错位置、报错信息（重要, 可以直接截个图）等
> 
> **版本信息**
> pytorch:
> torchvision:
> torchtext:
> ...

load_data_fashion_mnist 的完整实现详见 5.6.3

**Comment by fzcz** [comment]
谢谢，已经解决了



---Original---

**Comment by Nannan1104** [comment]
怎么解决的呀
