### ISSUE TITLE
docs文件夹下第二章的2.3节的文件讲梯度哪里好像显示出来有点问题

### ISSUE THREAD

**Issue by chaotianjiao** [ShusenTang/Dive-into-DL-PyTorch#71]
梯度哪里有一堆类似如下的符号：
数学上，如果有一个函数值和自变量都为向量的函数 $\vec{y}=f(\vec{x})$, 那么 $\vec{y}$ 关于 $\vec{x}$ 的梯度就是一个雅可比矩阵（Jacobian matrix）:
$$
J=\left(\begin{array}{ccc}
   \frac{\partial y_{1}}{\partial x_{1}} & \cdots & \frac{\partial y_{1}}{\partial x_{n}}\\
   \vdots & \ddots & \vdots\\
   \frac{\partial y_{m}}{\partial x_{1}} & \cdots & \frac{\partial y_{m}}{\partial x_{n}}
   \end{array}\right)

看不太懂，可否修正一下？

**Comment by ShusenTang** [comment]
github原生md不支持latex代码，readme里面说了，请前往网页版查看http://tangshusen.me/Dive-into-DL-PyTorch/#/chapter02_prerequisite/2.3_autograd

**Comment by chaotianjiao** [comment]
好的，好的，谢谢大佬，是我粗心了
