### ISSUE TITLE
书中seq2seq + Attention部分有一些代码是基于size间相等的前提写的，which is not always true.

### ISSUE THREAD

**Issue by SephiHorse** [ShusenTang/Dive-into-DL-PyTorch#72]
![image](https://user-images.githubusercontent.com/47956194/70623786-cb7f3500-1c59-11ea-9aa0-9fc3f18efc3e.png)

比如这个attention前向传播的代码，这里是默认encoder_hidden_size == decoder_hidden_size，所以下面红线处input_size 才能用2倍num_hiddens来赋值，并且上面红线处才可以直接dec_state.expand_as(enc_state)。

![image](https://user-images.githubusercontent.com/47956194/70624032-5102e500-1c5a-11ea-9c89-a36383ce7779.png)
这边又默认了hidden_size == embedding_size，所以decoder中的input_size 才能用2倍embedding_size来赋值。

我感觉这里是不是写的更具有普遍性会比较好，否则容易误导读者，我一开始就纳闷了很久为什么是*2。

**Comment by ShusenTang** [comment]
嗯，你说得对，之前也有人提出了（#64），所以我在前段时间已经修改了这个bug，参见 a86f344 ，你可以去看看最新的

**Comment by SephiHorse** [comment]
> 嗯，你说得对，之前也有人提出了（#64），所以我在前段时间已经修改了这个bug，参见 [a86f344](https://github.com/ShusenTang/Dive-into-DL-PyTorch/commit/a86f344ab988311ea839899ab722d74577398e86) ，你可以去看看最新的

好的，多谢
