### ISSUE TITLE
Chapter 2.3.2 梯度 - 变量描述错误

### ISSUE THREAD

**Issue by shisigang** [ShusenTang/Dive-into-DL-PyTorch#73]
**bug描述**
Chapter 2.3.2 梯度

![image](https://user-images.githubusercontent.com/38641789/70679580-864a1a00-1cd0-11ea-9602-02c2b9b53b4e.png)

**版本信息**
pytorch:
torchvision:
torchtext:
...

**Comment by ShusenTang** [comment]
感谢提醒，已修改
