### ISSUE TITLE
第5章第8节NiN网络中的函数(NameError: name 'F' is not defined)

### ISSUE THREAD

**Issue by chaotianjiao** [ShusenTang/Dive-into-DL-PyTorch#79]
class GlobalAvgPool2d(nn.Module):
    # 全局平均池化层可通过将池化窗口形状设置成输入的高和宽实现
    def __init__(self):
        super(GlobalAvgPool2d, self).__init__()
    def forward(self, x):
        return F.avg_pool2d(x, kernel_size=x.size()[2:])

使用这个类的时候一直显示F.is not defined.直接从d2lzh_pytorch中调用也是显示F.is not defined
想请问一下是我自己的问题还是代码的问题？谢谢~

**Comment by ShusenTang** [comment]
这个F就是`import torch.nn.functional`，需要用`import torch.nn.functional as F`导入

**Comment by ShusenTang** [comment]
这个F就是`torch.nn.functional`，可能忘了导入，用`import torch.nn.functional as F`导入即可

**Comment by chaotianjiao** [comment]
已在大佬指导下成功解决，谢谢大佬~ღ( ´･ᴗ･` )
