### ISSUE TITLE
李沐，这事怎么搞成“为他人作嫁衣裳”啦~~

### ISSUE THREAD

**Issue by cinastanbean** [ShusenTang/Dive-into-DL-PyTorch#8]

**Comment by wangzhe258369** [comment]
沐神看了想打人

**Comment by Redbaron0601** [comment]
我刚刚已经检查了自己的repo，已经轻掉了上午的fork，实在不好意思，是我没有好好的阅读开源指导，给您造成的困扰请您原谅，我也是今天刚翻到这个项目，看到了别人的推广，所以点进来查看，因为上午没有看开源指导，所以擅自就fork了一下，刚刚您的邮件让我意识到了问题的严重性，所以我向您表示道歉，真的对不起。请您放心，所有的repo已经被删除了，我会接着阅读您的项目，但不会这么莽撞的不跟您商量就擅自fork新版本，请您见谅。

在 2019-09-17 14:05:34，"Wangzhe" <notifications@github.com> 写道：


沐神看了想打人
