### ISSUE TITLE
3.2.2读取数据一节 调用data_iter时报错提示对象不可迭代

### ISSUE THREAD

**Issue by CharlieWY** [ShusenTang/Dive-into-DL-PyTorch#80]
因为是小白，这里的bug迟迟无法解决，还望各位大佬不吝赐教啊。
（1）问题：
执行这段代码：
batch_size = 10
for X, y in data_iter(batch_size, features, labels):
    print(X, '\n', y)
    break
（2）报错：
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-82-f5efc5a58268> in <module>()
      1 batch_size = 10
      2 
----> 3 for X, y in data_iter(batch_size, features, labels):
      4     print(X, '\n', y)
      5     break

TypeError: 'NoneType' object is not iterable

**Comment by ShusenTang** [comment]
要学会读bug，你这里bug提示你`data_iter(batch_size, features, labels)`的类型是`NoneType `，但是很明显正确的话它应该是个可迭代器，因为它的定义就是不断yield出x和y:
![image](https://user-images.githubusercontent.com/16498688/71612233-ef3ef680-2bd9-11ea-86e4-fab678243eb6.png)

所以你就检查一下你的`data_iter `是否出了问题

**Comment by CharlieWY** [comment]
> 要学会读bug，你这里bug提示你`data_iter(batch_size, features, labels)`的类型是`NoneType `，但是很明显正确的话它应该是个可迭代器，因为它的定义就是不断yield出x和y:
> ![image](https://user-images.githubusercontent.com/16498688/71612233-ef3ef680-2bd9-11ea-86e4-fab678243eb6.png)
> 
> 所以你就检查一下你的`data_iter `是否出了问题

已解决了，谢谢
