### ISSUE TITLE
您好，在章节3.7中有个疑惑

### ISSUE THREAD

**Issue by JadenFK** [ShusenTang/Dive-into-DL-PyTorch#82]
章节3.7中，3.7.2，您写到是“在3.4节(softmax回归)中提到，softmax回归的输出层是一个全连接层，所以我们用一个线性模块就可以了”。在后面的实现中，您也是用了一个nn.Linear()，但是softmax一个重要的地方是将输出值变换成值为正且和为1，但是我没有在3.7的代码里找到呀，是不是不能称之为softmax回归了呢？

**Comment by ShusenTang** [comment]
是这样的，3.7.3解释了，`CrossEntropyLoss`损失函数会帮我们进行你说的这一步。你可以去仔细看一下`CrossEntropyLoss`的文档。

**Comment by Siji-chl** [comment]
感谢作者的解答，nn.CrossEntropyLoss()是nn.logSoftmax()和nn.NLLLoss()的整合。
