### ISSUE TITLE
勘误个无关紧要的希望项目越来越好

### ISSUE THREAD

**Issue by zzuruichao** [ShusenTang/Dive-into-DL-PyTorch#84]
![微信图片_20200102195944](https://user-images.githubusercontent.com/58239273/71666097-72a74600-2d9a-11ea-9732-579f698a9760.png)
情感分析RNN里面的
oov_count += 0 应该是 oov_count += 1
下面输出语句忘了加 %oov_count了

**Comment by ShusenTang** [comment]
感谢提醒，已更正。
