### ISSUE TITLE
章节2.2 数据操作

### ISSUE THREAD

**Issue by FireJohnny** [ShusenTang/Dive-into-DL-PyTorch#85]
**bug描述**
章节2.2中，我在使用x.view()时，然后在修改x中的值，并未看到数据共享的情况，
![image](https://user-images.githubusercontent.com/19511703/71805065-2c0a6200-30a0-11ea-923c-10957a8c3c30.png)

![image](https://user-images.githubusercontent.com/19511703/71805030-17c66500-30a0-11ea-8785-8b3ba68584d3.png)

**版本信息**
pytorch: 1.1.0
torchvision:0.3.0
torchtext:未安装
...

**Comment by ShusenTang** [comment]
你仔细读一下2.2.4节就明白了。`z = z + 1`会开辟新的内存将z指向新内存。你可以试试如果用`z += 1`或者`z[:] = z + 1`的话x会不会跟着改变。

**Comment by FireJohnny** [comment]
是我粗心了
