### ISSUE TITLE
皮卡丘的数据集

### ISSUE THREAD

**Issue by chaotianjiao** [ShusenTang/Dive-into-DL-PyTorch#90]
![image](https://user-images.githubusercontent.com/42534375/72236598-9415f680-3612-11ea-84be-0f8d393a886f.png)
网站点进去是这样的，另外代码里面跑一直卡在下面那张图里不动
![image](https://user-images.githubusercontent.com/42534375/72236635-b60f7900-3612-11ea-8fd6-a887b8155b1d.png)
是我网络的问题吗？还是有其他解决的办法，谢谢大佬~

**Comment by ShusenTang** [comment]
下载`train.rec`的网址是`https://apache-mxnet.s3-accelerate.amazonaws.com/gluon/dataset/pikachu/train.rec`，下载`train.idx`和`val.rec`类似。

另外也可以直接运行那个代码，`Downloading.....`就是告诉你正在下载....数据集有点大，建议耐心等待

**Comment by chaotianjiao** [comment]
oh~oh~oh~  原来是这样，谢谢大佬
