### ISSUE TITLE
3.16中的rmse的损失计算

### ISSUE THREAD

**Issue by Sunstin** [ShusenTang/Dive-into-DL-PyTorch#97]
**bug描述**
 rmse = torch.sqrt(2 * loss(clipped_preds.log(), labels.log()).mean())
根据公式可以理解，loss()函数是计算MSE，求平均也好理解，为什么要乘以2，求解答，感谢~

**版本信息**
pytorch:
torchvision:
torchtext:
...

**Comment by WenhuiHan** [comment]
MSE已经求过平均，返回的是一个数字，rmse再求平均，返回的也是该数字本身，为什么还要求mean？
乘以2是因为这样吧
<a href="https://www.codecogs.com/eqnedit.php?latex=l_n&space;=&space;\frac{2}{N}\sum_{n=1}^{N}\left(&space;x_n&space;-&space;y_n&space;\right)^2" target="_blank"><img src="https://latex.codecogs.com/gif.latex?l_n&space;=&space;\frac{2}{N}\sum_{n=1}^{N}\left(&space;x_n&space;-&space;y_n&space;\right)^2" title="l_n = \frac{2}{N}\sum_{n=1}^{N}\left( x_n - y_n \right)^2" /></a>

**Comment by ShusenTang** [comment]
> **bug描述**
> rmse = torch.sqrt(2 * loss(clipped_preds.log(), labels.log()).mean())
> 根据公式可以理解，loss()函数是计算MSE，求平均也好理解，为什么要乘以2，求解答，感谢~
> 
> **版本信息**
> pytorch:
> torchvision:
> torchtext:
> ...

这里不应该乘以2. 原书乘以2是因为mxnet的L2loss除以了2所以要乘回来，但是PyTorch的MSELoss没除2所以不用乘了，已更正，感谢指正。

**Comment by ShusenTang** [comment]
> MSE已经求过平均，返回的是一个数字，rmse再求平均，返回的也是该数字本身，为什么还要求mean？
> 乘以2是因为这样吧
> [![](https://camo.githubusercontent.com/c7916054a2cf6544772327c6125e2de97b88d51d/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f6769662e6c617465783f6c5f6e2673706163653b3d2673706163653b5c667261637b327d7b4e7d5c73756d5f7b6e3d317d5e7b4e7d5c6c656674282673706163653b785f6e2673706163653b2d2673706163653b795f6e2673706163653b5c7269676874295e32)](https://www.codecogs.com/eqnedit.php?latex=l_n&space;=&space;\frac{2}{N}\sum_{n=1}^{N}\left(&space;x_n&space;-&space;y_n&space;\right)^2)

感谢指正，已更正。

**Comment by ghost** [comment]
https://github.com/ShusenTang/Dive-into-DL-PyTorch/issues/97#issue-562136303
